# Generated by Django 4.1.6 on 2023-05-06 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation_block',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('claims', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('claim', models.CharField(max_length=1000)),
                ('label', models.CharField(max_length=100)),
                ('supports', models.FloatField(null=True)),
                ('refutes', models.FloatField(null=True)),
                ('ei', models.FloatField(null=True)),
                ('nei', models.FloatField(null=True)),
                ('evidence', models.TextField(null=True)),
                ('justify', models.TextField(null=True)),
                ('evaluation_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluation_block')),
            ],
        ),
    ]
