# Generated by Django 4.1.3 on 2023-01-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='summary',
            field=models.TextField(default="That's actually cool"),
        ),
    ]
