# Generated by Django 4.1.3 on 2023-01-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_homepage_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
